import ROOT

def read_and_write(file):
    tfile = ROOT.TFile(file)
    keys = tfile.GetListOfKeys()
    new_tfile=ROOT.TFile("new_data.root", "RECREATE")
    mt=tfile.Get(keys[0].GetName())
    met=tfile.Get(keys[1].GetName())
    lpt=tfile.Get(keys[2].GetName())
    leta=tfile.Get(keys[3].GetName())
    mt_tight=tfile.Get(keys[4].GetName())
    met_tight=tfile.Get(keys[5].GetName())
    lpt_tight=tfile.Get(keys[6].GetName())
    leta_tight=tfile.Get(keys[7].GetName())
    mt_kin=tfile.Get(keys[8].GetName())
    met_kin=tfile.Get(keys[9].GetName())
    lpt_kin=tfile.Get(keys[10].GetName())
    leta_kin=tfile.Get(keys[11].GetName())
    mt_kin_tight=tfile.Get(keys[12].GetName())
    met_kin_tight=tfile.Get(keys[13].GetName())
    lpt_kin_tight=tfile.Get(keys[14].GetName())
    leta_kin_tight=tfile.Get(keys[15].GetName())
    dphi=tfile.Get(keys[16].GetName())
    dphi_tight=tfile.Get(keys[17].GetName())
    pt_mt_2D=tfile.Get(keys[18].GetName())
    pt_mt_2D_tight=tfile.Get(keys[19].GetName())
    pt_eta_2D=tfile.Get(keys[20].GetName())
    pt_eta_2D_tight=tfile.Get(keys[21].GetName())
    pt_phi_2D=tfile.Get(keys[22].GetName())
    pt_phi_2D_tight=tfile.Get(keys[23].GetName())
    mclumi=tfile.Get(keys[24].GetName())

    # add the fake lepton estimation in the tight
    mt.Add(mt_tight, -1)
    met.Add(met_tight, -1)
    lpt.Add(lpt_tight, -1)
    leta.Add(leta_tight, -1)
    mt_kin.Add(mt_kin_tight, -1)
    met_kin.Add(met_kin_tight, -1)
    lpt_kin.Add(lpt_kin_tight, -1)
    leta_kin.Add(leta_kin_tight, -1)
    mt_tight=mt.Clone()


    mt.Write()
    met.Write()
    lpt.Write()
    leta.Write()
    mt_tight.Write()
    met_tight.Write()
    lpt_tight.Write()
    leta_tight.Write()
    mt_kin.Write()
    met_kin.Write()
    lpt_kin.Write()
    leta_kin.Write()
    mt_kin_tight.Write()
    met_kin_tight.Write()
    lpt_kin_tight.Write()
    leta_kin_tight.Write()
    dphi.Write()
    dphi_tight.Write()
    pt_mt_2D.Write()
    pt_mt_2D_tight.Write()
    pt_eta_2D.Write()
    pt_eta_2D_tight.Write()
    pt_phi_2D.Write()
    pt_phi_2D_tight.Write()
    mclumi.Write()


    #for key in keys:
        #print(key.GetName())
        #key.Write()

if __name__ == '__main__':
    file='data.root'
    read_and_write(file)
